---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: kibana
spec:
  chart:
    spec:
      chart: kibana
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: kibana
  interval: 1m0s

