---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: kibana
  namespace: kibana
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/elastic/helm-charts

