---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector
  namespace: vector
spec:
  chart:
    spec:
      chart: vector/vector
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: vector
  interval: 1m0s
  releaseName: vector
  values:
    replicaCount: 3

