---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector
  namespace: vector
spec:
  chart:
    spec:
      chart: charts/vector
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: vector
  interval: 1m0s

